import yaml
from pathlib import Path
# from snakemake import workflow


# =================================================================================================
#     Common
# =================================================================================================


# We first need to load the common functionality, which gives us access to the config file,
# generates the sample list, and prepares some other things for us that are needed below.
include: "rules/initialize.smk"


# =================================================================================================
#     Default "All" Target Rule
# =================================================================================================


# The rule that is executed by default. We include the result files of different intermediate steps
# here as well, for example, the genotyped vcf file from the "calling.smk" step, so that a nice
# arrow shows up in the DAG that reminds us that this is an important intermediate file.
rule all:
    input:
        # Basic steps
        "mapping/final.done",
        "calling/genotyped-all.vcf.gz",
        "calling/genotyped-all.vcf.gz.done",
        "calling/filtered-all.vcf.gz" if not config["settings"]["filter-variants"] == "none" else [],
        "calling/filtered-all.vcf.gz.done"
        if not config["settings"]["filter-variants"] == "none"
        else [],
        "annotation/snpeff.vcf.gz" if config["settings"]["snpeff"] else [],
        "annotation/snpeff.vcf.gz.done" if config["settings"]["snpeff"] else [],
        "annotation/vep.vcf.gz" if config["settings"]["vep"] else [],
        "annotation/vep.vcf.gz.done" if config["settings"]["vep"] else [],
        # Quality control
        "qc/multiqc.html",
        # Reference genome statistics
        config["data"]["reference-genome"] + ".seqkit",
        # Pileup
        "mpileup/all-pileups.done" if len(config["settings"]["pileups"]) else [],
        # HAFpipe
        "hafpipe/all.csv"
        + (".gz" if config["params"]["hafpipe"].get("compress-merged-table", False) else "")
        if config["settings"]["hafpipe"]
        else [],
        # Stats. Some deactivated for now.
        "tables/frequencies.tsv" if config["settings"]["frequency-table"] else [],
        # "plots/depths.svg",
        # "plots/allele-freqs.svg",
        # "tables/sample-sizes.tsv"


# The main `all` rule is local. It does not do anything anyway,
# except requesting the other rules to run.
localrules:
    all,


# =================================================================================================
#     Rule Modules
# =================================================================================================

# These rules need to come after the `all` rule above, as Snakemake takes the first rule it finds
# as the implicit target when no other target is specified, and we want that to be the `all` rule.


include: "rules/prepare-reference.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/annotation.smk"
include: "rules/qc.smk"
include: "rules/stats.smk"
include: "rules/damage.smk"
include: "rules/pileup.smk"
include: "rules/frequency.smk"


# =================================================================================================
#     Resources
# =================================================================================================


# Helper function to compute the resources needed for rule
# based on the input file sizes and the resource config.
def make_resource_fn(rule_name, kind):
    """
    returns fn(wildcards, input_files) -> int(resource)
    which will:
      - sum up sizes of input files
      - pick an offset and scaler (rule override or default)
      - return int(offset + size * scaler), scaled by attempt
    kind should be "mem" or "time", and expects in resources_config:
    - <kind>_offset
    - <kind>_scaler
    - <kind>_max
    """
    def _fn(wildcards, inputs=[], threads=None, attempt=1):
        # Config keys (mem or time)
        o_key = f"{kind}-offset"
        s_key = f"{kind}-scaler"
        m_key = f"{kind}-max"
        f_key = f"attempt-factor"

        # Look up the config values or their defaults.
        rule_cfg = resources_config.get(rule_name, {})
        scaler = rule_cfg.get(s_key, resources_config["default"][s_key])
        offset = rule_cfg.get(o_key, resources_config["default"][o_key])
        factor = rule_cfg.get(f_key, resources_config["default"][f_key])
        capped = rule_cfg.get(m_key, resources_config["default"][m_key])

        # Compute the total file size in MB
        total = sum(Path(f).stat().st_size for f in inputs) / 1000000.0

        # Compute the resource value, capping it at the max.
        mul = factor ** (attempt - 1)
        val = mul * (offset + total * scaler)
        if capped is not None and val > capped:
            logger.warning(f"[{rule_name}] {kind} {val:.1f} exceeds max {capped}; capping")
            val = capped
        return int(val)
    return _fn


# Set the resources for all rules automatically,
# without having to specify this for all of them individually.
# We also re-set the threads here, just in case.
# Cannot name the iteration variable `rule` here, as that conflicts...
for wf_rule in workflow.rules:
    wf_rule.resources["mem_mb"]  = make_resource_fn(wf_rule.name, "mem")
    wf_rule.resources["runtime"] = make_resource_fn(wf_rule.name, "time")
    wf_rule.threads = get_rule_threads(wf_rule.name)
