$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file for the grenepipe workflow

type: object

properties:
  data:
    type: object
    properties:
      samples-table:
        type: string
      samples-count:
        type: integer
      reference-genome:
        type: string
      known-variants:
        type: string
    required:
      - samples-table
      - reference-genome
      - known-variants

  settings:
    type: object
    properties:
      trimming-tool:
        type: string
        enum: ["adapterremoval", "cutadapt", "fastp", "trimmomatic", "seqprep", "skewer", "none"]
      merge-paired-end-reads:
        type: boolean
      mapping-tool:
        type: string
        enum: ["bowtie2", "bwaaln", "bwamem", "bwamem2"]
      filter-mapped-reads:
        type: boolean
      clip-read-overlaps:
        type: boolean
      remove-duplicates:
        type: boolean
      duplicates-tool:
        type: string
        enum: ["picard", "dedup"]
      recalibrate-base-qualities:
        type: boolean
      calling-tool:
        type: string
        enum: ["haplotypecaller", "freebayes", "bcftools"]
      restrict-regions:
        type: string
      contig-group-size:
        type: integer
      # region-padding:
      #   type: integer
      filter-variants:
        type: string
      keep-intermediate:
        type: object
        properties:
          trimming:
            type: boolean
          mapping:
            type: boolean
          calling:
            type: boolean
      snpeff:
        type: boolean
      vep:
        type: boolean
      mapdamage:
        type: boolean
      damageprofiler:
        type: boolean
      pileups:
        type:
          - array
      hafpipe:
        type: boolean
      frequency-table:
        type: boolean
    required:
      - trimming-tool
      - merge-paired-end-reads
      - mapping-tool
      - filter-mapped-reads
      - clip-read-overlaps
      - remove-duplicates
      - duplicates-tool
      - recalibrate-base-qualities
      - calling-tool
      - contig-group-size
      - restrict-regions
      - snpeff
      - vep
      - mapdamage
      - damageprofiler
      - pileups
      - hafpipe
      - frequency-table
      - frequency-table-fields

  params:
    type: object
    properties:
      adapterremoval:
        type: object
        properties:
          threads:
            type: integer
          se:
            type: string
          pe:
            type: string
      cutadapt:
        type: object
        properties:
          threads:
            type: integer
          se:
            type: object
          pe:
            type: object
      fastp:
        type: object
        properties:
          threads:
            type: integer
          se:
            type: string
          pe:
            type: string
      seqprep:
        type: object
        properties:
          extra:
            type: string
      skewer:
        type: object
        properties:
          threads:
            type: integer
          se:
            type: string
          pe:
            type: string
      trimmomatic:
        type: object
        properties:
          threads:
            type: integer
          se:
            type: object
          pe:
            type: object
      bowtie2:
        type: object
        properties:
          threads:
            type: integer
          extra:
            type: string
      bwaaln:
        type: object
        properties:
          threads:
            type: integer
          extra:
            type: string
          extra-sort:
            type: string
      bwamem:
        type: object
        properties:
          threads:
            type: integer
          extra:
            type: string
          extra-sort:
            type: string
      bwamem2:
        type: object
        properties:
          threads:
            type: integer
          extra:
            type: string
          extra-sort:
            type: string
      samtools:
        type: object
        properties:
          view:
            type: string
      bamutil:
        type: object
        properties:
          extra:
            type: string
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
          CollectMultipleMetrics:
            properties:
              # Old names
              AlignmentSummaryMetrics:
                type: boolean
              BaseDistributionByCycle:
                type: boolean
              GcBiasMetrics:
                type: boolean
              InsertSizeMetrics:
                type: boolean
              QualityByCycleMetrics:
                type: boolean
              QualityScoreDistributionMetrics:
                type: boolean
              QualityYieldMetrics:
                type: boolean

              # New names
              CollectAlignmentSummaryMetrics:
                type: boolean
              CollectBaseDistributionByCycle:
                type: boolean
              CollectGcBiasMetrics:
                type: boolean
              CollectInsertSizeMetrics:
                type: boolean
              CollectQualityYieldMetrics:
                type: boolean
              MeanQualityByCycle:
                type: boolean
              QualityScoreDistribution:
                type: boolean
              CollectSequencingArtifactMetrics:
                type: boolean
              RnaSeqMetrics:
                type: boolean
          CollectMultipleMetrics-extra:
            type: string
        required:
          - MarkDuplicates
          - CollectMultipleMetrics
          - CollectMultipleMetrics-extra
      dedup:
        type: object
        properties:
          extra:
            type: string
      bcftools:
        type: object
        properties:
          mpileup:
            type: string
          call:
            type: string
          threads:
            type: integer
          mode:
            type: string
          stats:
            type: string
          stats-plot:
            type: string
          # concat:
          #   type: string
      freebayes:
        type: object
        properties:
          extra:
            type: string
          chunksize:
            type: integer
          threads:
            type: integer
          compress-threads:
            type: integer
      gatk:
        type: object
        properties:
          BaseRecalibrator:
            type: string
          HaplotypeCaller-extra:
            type: string
          CombineGVCFs-extra:
            type: string
          GenotypeGVCFs-extra:
            type: string
          HaplotypeCaller-java-opts:
            type: string
          CombineGVCFs-java-opts:
            type: string
          GenotypeGVCFs-java-opts:
            type: string
          HaplotypeCaller-threads:
            type: integer
        required:
          - CombineGVCFs-extra
          - GenotypeGVCFs-extra
      gatk-variantfiltration:
        type: object
        properties:
          SNP:
            type: string
          INDEL:
            type: string
          extra:
            type: string
        required:
          - SNP
          - INDEL
          - extra
      gatk-vqsr:
        type: object
        properties:
          resources:
            type: [array, object]
          resource-files:
            type: [array, object]
          annotation:
            type: [array, object]
          extra-variantrecalibrator-SNP:
            type: string
          extra-variantrecalibrator-INDEL:
            type: string
          java-variantrecalibrator:
            type: string
          extra-applyvqsr-SNP:
            type: string
          extra-applyvqsr-INDEL:
            type: string
          java-applyvqsr:
            type: string
      bcftools-filter:
        type: object
        properties:
          SNP:
            type: string
          INDEL:
            type: string
          extra:
            type: string
        required:
          - SNP
          - INDEL
          - extra
      fastqc:
        type: object
        properties:
          input:
            type: string
          extra:
            type: string
      qualimap:
        type: object
        properties:
          bams:
            type: string
          extra:
            type: string
          threads:
            type: integer
      snpeff:
        type: object
        properties:
          name:
            type: string
          download-dir:
            type: string
          custom-db-dir:
            type: string
          extra:
            type: string
      mapdamage:
        type: object
        properties:
          extra:
            type: string
      damageprofiler:
        type: object
        properties:
          extra:
            type: string
      seqkit:
        type: object
        properties:
          extra:
            type: string
      multiqc:
        type: object
        properties:
          extra:
            type: string
    required:
      - adapterremoval
      - cutadapt
      - fastp
      - seqprep
      - trimmomatic
      - skewer
      - bowtie2
      - bwaaln
      - bwamem
      - bwamem2
      - samtools
      - picard
      - dedup
      - bcftools
      - freebayes
      - gatk
      - gatk-variantfiltration
      - gatk-vqsr
      - bcftools-filter
      - fastqc
      - qualimap
      - snpeff
      - vep
      - mapdamage
      - damageprofiler
      - seqkit
      - multiqc

required:
  - data
  - settings
  - params
